#############################################################################
# Makefile for building: platform_mac/debug/Lightrus.app/Contents/MacOS/Lightrus
# Generated by qmake (2.01a) (Qt 4.5.1) on: ?? ??? 25 23:06:04 2009
# Project:  Lightrus.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile Lightrus.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.5/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -Iinc -Igenerated -Igenerated -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = platform_mac/debug/obj/

####### Files

SOURCES       = src/main.cpp \
		src/maindialog.cpp \
		src/infocollector.cpp \
		src/translator.cpp \
		src/controller.cpp \
		src/model.cpp \
		src/modelhelper.cpp generated/moc_maindialog.cpp \
		generated/moc_translator.cpp \
		generated/moc_controller.cpp \
		generated/moc_model.cpp \
		generated/moc_logobject.cpp \
		generated/qrc_res.cpp
OBJECTS       = platform_mac/debug/obj/main.o \
		platform_mac/debug/obj/maindialog.o \
		platform_mac/debug/obj/infocollector.o \
		platform_mac/debug/obj/translator.o \
		platform_mac/debug/obj/controller.o \
		platform_mac/debug/obj/model.o \
		platform_mac/debug/obj/modelhelper.o \
		platform_mac/debug/obj/moc_maindialog.o \
		platform_mac/debug/obj/moc_translator.o \
		platform_mac/debug/obj/moc_controller.o \
		platform_mac/debug/obj/moc_model.o \
		platform_mac/debug/obj/moc_logobject.o \
		platform_mac/debug/obj/qrc_res.o
DIST          = /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		Lightrus.pro
QMAKE_TARGET  = Lightrus
DESTDIR       = platform_mac/debug/
TARGET        = platform_mac/debug/Lightrus.app/Contents/MacOS/Lightrus

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile platform_mac/debug/Lightrus.app/Contents/PkgInfo platform_mac/debug/Lightrus.app/Contents/Resources/empty.lproj platform_mac/debug/Lightrus.app/Contents/Info.plist platform_mac/debug/Lightrus.app/Contents/Resources/app.icns $(TARGET)

$(TARGET): generated/ui_maindialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) platform_mac/debug/Lightrus.app/Contents/MacOS/ || $(MKDIR) platform_mac/debug/Lightrus.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Lightrus.pro  /usr/local/Qt4.5/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile Lightrus.pro
/usr/local/Qt4.5/mkspecs/common/unix.conf:
/usr/local/Qt4.5/mkspecs/common/mac.conf:
/usr/local/Qt4.5/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.5/mkspecs/qconfig.pri:
/usr/local/Qt4.5/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.5/mkspecs/features/qt_config.prf:
/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.5/mkspecs/features/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.5/mkspecs/features/debug.prf:
/usr/local/Qt4.5/mkspecs/features/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.5/mkspecs/features/warn_on.prf:
/usr/local/Qt4.5/mkspecs/features/qt.prf:
/usr/local/Qt4.5/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.5/mkspecs/features/moc.prf:
/usr/local/Qt4.5/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.5/mkspecs/features/resources.prf:
/usr/local/Qt4.5/mkspecs/features/uic.prf:
/usr/local/Qt4.5/mkspecs/features/yacc.prf:
/usr/local/Qt4.5/mkspecs/features/lex.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile Lightrus.pro

platform_mac/debug/Lightrus.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) platform_mac/debug/Lightrus.app/Contents || $(MKDIR) platform_mac/debug/Lightrus.app/Contents 
	@$(DEL_FILE) platform_mac/debug/Lightrus.app/Contents/PkgInfo
	@echo "APPL????" >platform_mac/debug/Lightrus.app/Contents/PkgInfo
platform_mac/debug/Lightrus.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) platform_mac/debug/Lightrus.app/Contents/Resources || $(MKDIR) platform_mac/debug/Lightrus.app/Contents/Resources 
	@touch platform_mac/debug/Lightrus.app/Contents/Resources/empty.lproj
	
platform_mac/debug/Lightrus.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) platform_mac/debug/Lightrus.app/Contents || $(MKDIR) platform_mac/debug/Lightrus.app/Contents 
	@$(DEL_FILE) platform_mac/debug/Lightrus.app/Contents/Info.plist
	@sed -e "s,@ICON@,app.icns,g" -e "s,@EXECUTABLE@,Lightrus,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.5/mkspecs/macx-g++/Info.plist.app >platform_mac/debug/Lightrus.app/Contents/Info.plist
platform_mac/debug/Lightrus.app/Contents/Resources/app.icns: platform_mac/app.icns
	@$(CHK_DIR_EXISTS) platform_mac/debug/Lightrus.app/Contents/Resources/ || $(MKDIR) platform_mac/debug/Lightrus.app/Contents/Resources/ 
	@$(DEL_FILE) platform_mac/debug/Lightrus.app/Contents/Resources/app.icns
	@$(COPY_FILE) platform_mac/app.icns platform_mac/debug/Lightrus.app/Contents/Resources/app.icns
dist: 
	@$(CHK_DIR_EXISTS) platform_mac/debug/obj/Lightrus1.0.0 || $(MKDIR) platform_mac/debug/obj/Lightrus1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) platform_mac/debug/obj/Lightrus1.0.0/ && $(COPY_FILE) --parents inc/maindialog.h inc/infocollector.h inc/translator.h inc/constants.h inc/controller.h inc/model.h inc/modelhelper.h inc/logobject.h platform_mac/debug/obj/Lightrus1.0.0/ && $(COPY_FILE) --parents res.qrc platform_mac/debug/obj/Lightrus1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/maindialog.cpp src/infocollector.cpp src/translator.cpp src/controller.cpp src/model.cpp src/modelhelper.cpp platform_mac/debug/obj/Lightrus1.0.0/ && $(COPY_FILE) --parents maindialog.ui platform_mac/debug/obj/Lightrus1.0.0/ && (cd `dirname platform_mac/debug/obj/Lightrus1.0.0` && $(TAR) Lightrus1.0.0.tar Lightrus1.0.0 && $(COMPRESS) Lightrus1.0.0.tar) && $(MOVE) `dirname platform_mac/debug/obj/Lightrus1.0.0`/Lightrus1.0.0.tar.gz . && $(DEL_FILE) -r platform_mac/debug/obj/Lightrus1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r platform_mac/debug/Lightrus.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: generated/moc_maindialog.cpp generated/moc_translator.cpp generated/moc_controller.cpp generated/moc_model.cpp generated/moc_logobject.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) generated/moc_maindialog.cpp generated/moc_translator.cpp generated/moc_controller.cpp generated/moc_model.cpp generated/moc_logobject.cpp
generated/moc_maindialog.cpp: inc/maindialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/maindialog.h -o generated/moc_maindialog.cpp

generated/moc_translator.cpp: inc/logobject.h \
		inc/translator.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/translator.h -o generated/moc_translator.cpp

generated/moc_controller.cpp: inc/controller.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/controller.h -o generated/moc_controller.cpp

generated/moc_model.cpp: inc/logobject.h \
		inc/model.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/model.h -o generated/moc_model.cpp

generated/moc_logobject.cpp: inc/logobject.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ inc/logobject.h -o generated/moc_logobject.cpp

compiler_rcc_make_all: generated/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) generated/qrc_res.cpp
generated/qrc_res.cpp: res.qrc \
		res/text/russian_dictionary.txt \
		res/text/readme_rus.txt \
		res/text/english_exclusions.txt \
		res/images/top_logo.png \
		res/images/app.ico \
		res/images/side_logo.png
	/Developer/Tools/Qt/rcc -name res res.qrc -o generated/qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: generated/ui_maindialog.h
compiler_uic_clean:
	-$(DEL_FILE) generated/ui_maindialog.h
generated/ui_maindialog.h: maindialog.ui
	/Developer/Tools/Qt/uic maindialog.ui -o generated/ui_maindialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

platform_mac/debug/obj/main.o: src/main.cpp inc/model.h \
		inc/logobject.h \
		inc/maindialog.h \
		inc/controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/main.o src/main.cpp

platform_mac/debug/obj/maindialog.o: src/maindialog.cpp inc/maindialog.h \
		generated/ui_maindialog.h \
		inc/infocollector.h \
		inc/translator.h \
		inc/logobject.h \
		inc/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/maindialog.o src/maindialog.cpp

platform_mac/debug/obj/infocollector.o: src/infocollector.cpp inc/infocollector.h \
		inc/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/infocollector.o src/infocollector.cpp

platform_mac/debug/obj/translator.o: src/translator.cpp inc/translator.h \
		inc/logobject.h \
		inc/constants.h \
		inc/infocollector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/translator.o src/translator.cpp

platform_mac/debug/obj/controller.o: src/controller.cpp inc/controller.h \
		inc/maindialog.h \
		inc/model.h \
		inc/logobject.h \
		inc/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/controller.o src/controller.cpp

platform_mac/debug/obj/model.o: src/model.cpp inc/model.h \
		inc/logobject.h \
		inc/translator.h \
		inc/infocollector.h \
		inc/modelhelper.h \
		inc/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/model.o src/model.cpp

platform_mac/debug/obj/modelhelper.o: src/modelhelper.cpp inc/modelhelper.h \
		inc/logobject.h \
		inc/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/modelhelper.o src/modelhelper.cpp

platform_mac/debug/obj/moc_maindialog.o: generated/moc_maindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/moc_maindialog.o generated/moc_maindialog.cpp

platform_mac/debug/obj/moc_translator.o: generated/moc_translator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/moc_translator.o generated/moc_translator.cpp

platform_mac/debug/obj/moc_controller.o: generated/moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/moc_controller.o generated/moc_controller.cpp

platform_mac/debug/obj/moc_model.o: generated/moc_model.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/moc_model.o generated/moc_model.cpp

platform_mac/debug/obj/moc_logobject.o: generated/moc_logobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/moc_logobject.o generated/moc_logobject.cpp

platform_mac/debug/obj/qrc_res.o: generated/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform_mac/debug/obj/qrc_res.o generated/qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

